### ISSUE TITLE
Counter: Remove Wordpress dependency

### ISSUE THREAD

**Issue by matthib** [Human-Connection/Clock-of-Change-Frontend#10]
**Problem:** 
Currently the counter is integrated as a plugin in Wordpress. This means that in order to embed the counter anywhere, you always have to have a full Wordpress system with the specific plugin and theme running.
As we want to make it possible to embed the counter on third party websites and under its own domain, we need to find a solution for that.

**Solution:**
We need to detach the counter from the Wordpress context and cut all the dependencies, so it can be embedded on any website as a standalone microservice.

See https://human-connection.org/uhr-des-wandels/

**Comment by appinteractive** [comment]
Take a look 👀 at the coc widget here: https://team.human-connection.org/bitbucket/projects/HC/repos/hc-coc-widget/browse

**Comment by matthib** [comment]
@appinteractive Amazing! Didn't know there were also parts of the Clock of Change hosted on Bitbucket. 
That saves a lot of work 👍

**Comment by matthib** [comment]
@appinteractive The domain that the CoC widget depends upon http://widget.clockofchange.org/ seems to be down (Error 522). Do you know why?
